//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace curd_All.Datacon
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int id { get; set; }
        public string ename { get; set; }
        public string Email { get; set; }
        public string edept { get; set; }
    }
}
